#set( $symbol_dollar = '$' )
server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://${rootArtifactId}-gateway:6000/;
        proxy_set_header Host ${symbol_dollar}host;
        proxy_set_header X-Real-IP ${symbol_dollar}remote_addr;
        proxy_set_header X-Forwarded-For ${symbol_dollar}proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto ${symbol_dollar}scheme;
    }

    location / {
        try_files ${symbol_dollar}uri ${symbol_dollar}uri/ /index.html;
    }
}
