server:
  port: 4000

spring:
  profiles:
    active: @profile.active@
  application:
    name: macula-example-tencent-gateway
  config:
    import: optional:polaris
  cloud:
    nacos:
      discovery:
        server-addr: ${POLARIS_NACOS_SERVER_ADDR:127.0.0.1:18849}
    polaris:
      address: ${polaris.server-addr}
      namespace: ${polaris.namespace}
      config:
        auto-refresh: true
        groups:
          - name: ${spring.application.name}
      discovery:
        enabled: true

    gateway:
      server:
        webflux:
          routes:
            - id: macula-example-tencent-consumer
              uri: lb://macula-example-tencent-consumer
              predicates:
                - Path=/consumer/**
              filters:
                - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: e4da4a32-592b-46f0-ae1d-784310e88423
          client-secret: secret
          introspection-uri: ${OAUTH2_INTROSPECTION_URI:http://127.0.0.1:9010/oauth2/introspect}

macula:
  gateway:
    security:
      only-auth-urls: /api/**

# 和环境有关的配置信息，不同环境覆盖此处的配置
polaris:
  namespace: ${POLARIS_NAMESPACE:macula-dev}
  server-addr: ${POLARIS_SERVER_ADDR:grpc://127.0.0.1:8091}

logging:
  level:
    root: info
    dev.macula.example.gateway: debug
    dev.macula.boot.starter.cloud.gateway: debug
  file:
    name: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
  #config: classpath:logback-skywalking.xml
