server:
  port: 6002
  servlet:
    encoding:
      force: true

spring:
  profiles:
    active: @profile.active@
  application:
    name: ${rootArtifactId}-openapi
  config:
    import:
      - optional:nacos:${spring.application.name}.yml?refreshEnabled=true
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?refreshEnabled=true
  cloud:
    nacos:
      username: ${nacos.username}
      password: ${nacos.password}
      config:
        server-addr: ${nacos.config.server-addr}
        namespace: ${nacos.config.namespace}
        refresh-enabled: true
        file-extension: yml
      discovery:
        enabled: true
        server-addr: ${nacos.config.server-addr}
        namespace: ${nacos.config.namespace}
        # group:
    sentinel:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks    # 网关地址
feign:
  httpclient:
    enabled: false
    max-connections: 200          # 线程池最大连接数，默认200
    time-to-live: 900             # 线程存活时间，单位秒，默认900
    connection-timeout: 2000      # 新建连接超时时间，单位ms, 默认2000
    follow-redirects: true        # 是否允许重定向，默认true
    disable-ssl-validation: false # 是否禁止SSL检查， 默认false
    okhttp:
      read-timeout: 60s           # 请求超时时间，Duration配置方式
  okhttp:
    enabled: true
  sentinel:
    enabled: false

seata:
  enabled: false

springdoc:
  api-docs:
    enabled: true  # 默认是true，用于开关API文档
  swagger-ui:
    enabled: true # 默认是true，用于开关API UI

logging:
  level:
    root: info
    com.alibaba.nacos.client: error
  file:
    name: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log

# 和环境有关的配置信息，不同环境覆盖此处的配置（这个是本地环境）
nacos:
  username: ${symbol_dollar}{NACOS_USERNAME:nacos}
  password: ${symbol_dollar}{NACOS_PASSWORD:nacos}
  config:
    server-addr: ${symbol_dollar}{NACOS_SERVER_ADDR:127.0.0.1:8848}
    namespace: ${symbol_dollar}{NACOS_NAMESPACE:MACULA5}

---
spring:
  config:
    activate:
      on-profile: dev
nacos:
  username: maculav5
  #password: 请通过启动命令赋予密码
  config:
    server-addr: 10.94.108.55:8848
    namespace: MACULA5
